[package]
name = "npt-mobile-wallet"
version = "0.1.0"
description = "Neptune Mobile Wallet"
authors = ["you"]
edition = "2021"

[lib]
name = "npt_mobile_wallet_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1", features = ["full"] }

# Seed management
bip39 = "2.1"
aes-gcm = "0.10"
rand = "0.8"
hex = "0.4"
sha2 = "0.10"
zeroize = { version = "1", features = ["derive"] }
